language: php
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/bin
    - $HOME/.n98-magerun/modules
    - $HOME/.cache/magento
php:
- 5.5
- 5.6
- 7.0
matrix:
  fast_finish: true
  allow_failures:
  - php: 5.6
    env: MAGENTO_VERSION=ce-1.8.1.0
  - php: 7.0
    env: MAGENTO_VERSION=ce-1.8.1.0
env:
  global:
  - APPNAME=Ffuenf_OrderExporter
  - secure: VgaUOlKrin9zrx9QYLBC+MjuLKgWUWCib1NsbdvQKGLz+LbP01K+UV+fcG5Q8Dti37YEjNPB4NUZE8UXAJHxlbzjYXnh6nthPoOrXSkZqppM2sE0hd2K/HPrszb0zEJ9kUoNETG4vBE44WyaVqO+FyRaj1GYm/ZaBKn0Q/VrRhnxiPWzv6DCpVmNRMOSYq4mHiOyAQo0HEcBmwve2xqAbZ8QR0JnI1ewiRn2fMXqALMxJWkHrjHfFijq9jA/A605j968GLJKNLyF/MXhe8ita+Ihy+GV+S31gnc7CidHbPZDCJPrRd4h+1paKa0Xs0bpG056Ud8YoY7XPPY6yeTS75YVN1J74JbJPv/+dqBRlT2kpyvMHhKqhoXZnkt1ix5ZzVi8RmJTqhYjKvWgVLNTG2j9owmVNp+9lkUoGuezz/A7W7oiOPH+xrFyfLDCyjb051QARxOulkB8sl8TzvVfmmXS1rP1GHr9/MVkLnoyf2f/1Qw9qCncXDlUnijwMzZ/uHocbWkn3MF4XTBwcS0+ChPkbMeoAAHrpcHENUUMFiBamXpm+1+iCXlkg88md0voc+yYZ5YsZWsGlxDLPJdOxkRl264CfTeCq1h+w2TGFxzY3trQeRTn0BZ0XPaK2qqxfVu2X24dVZEhPIWFSUXBu9MqZHka4fNE0LlFoIg7/oo=
  - secure: VXPeFcFuSU/Iovtkyr4HhDUuKohaXVSeKGALYFlcRHCKLuSsHEf4oO+iOLCXMjieaWjBJo1rLF3Iieq1JV3F6O04hL/NuRtm8ZABgHFToEWTAqTzs12VB/i4yY4z247J4gW6NfoeUY0/UC0p8E3mUmK5rBzpwz+nbZ/iwdcKBjxV/EG1TIPzBSGmn4CO9jje6RS4rQhRiR3vxOLRbStZwoXTH71BMHjXmL5R4z6o/U+n5U95zBrRd2h1RaU2JBdWer2GBNSCEY3xuX8+2qgwg2u9JQ2dGuH+ubS5gbjiZ2FVaw+C2J3KxKh1SND+nXUWFKNE2TS70naZp6M5WSYTJyXq6NGpAmFmw5FhFURnChIFbLRVeqpu8z3v6X2jV8vLIrg7Wy4YG9Ov4RUJMuWdrtLR3GROxkxI6ScAfvX9FyK5MQOUUjcqQB82G1Q/QJWwSAhppi8b4wwku4oXjnFE1lCTI6jVqYPui61TWAYKhIbv0sN0DxYI6Mfiv/42JIPJ2b3RkrgbZ54A8EVt1lOVX67GKjMTKRKJKUcyGK3KnLxF1B2+iYFzrRrBuijDFyWdwE/3V+HQG2plCSyvm/+KhXP3NeeDNGW46FCkyinHu6RmoKQ5EmGTxAFV8RGfCUqWuM3PSjGNSYIZ3GEnCYKRvq4WafrraSpEjfRMt3jYfqE=
  matrix:
  - MAGENTO_VERSION=ce-1.9.2.4
  - MAGENTO_VERSION=ce-1.9.1.1
  - MAGENTO_VERSION=ce-1.8.1.0
  - MAGENTO_VERSION=ce-1.7.0.2
  - MAGENTO_VERSION=ce-1.6.2.0
before_install:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/before_install.sh
  | bash
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/script.sh
  | bash
deploy:
  provider: releases
  file:
  - "${APPNAME}-${TRAVIS_TAG}.zip"
  - "${APPNAME}-${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    branch: master
    tags: true
  api_key:
    secure: 0ejHufgFdWgUl3Hoa4FM8JeGuvNZDa+7AZRdw02EmWt+7nefP5iOhugmBneDLLLsXWUW4hKOJ/Wupc7DXjR+SLQlhaMb9E2ab5eyp7oROnFiQNxFl6UscaltDLbRAX+GmKUpcOspdpsMBO6a+suEQbo0rwQZOIyWOmxHnU3ZB4bsNj73wjUzffSPkFIDZCQDdimizr2MuDQWqZXa4nTkSSO8esdoiWv8dwn3zXdZwSLY6w1F1XvvpMa6bH8H9vGlLwrxWR1ODPZ2+oYciJW2RiHreFx38FgYo0W+G1wHWImVwp66Dr0Cj6YNXw5znIolbARwRf8kSDCvrF5x2S5lV39s7x/qXAsiq7xbuAMwP5iVxMFqIjqqiGeuWulg5Q3hPQaYqhlxpkKrqIFOyCmttAxmDn4gLV3rdJG6XOEccYAK52mNo9icW7TZSht4wECIbMtXZa3dUdC3bMwgT3c45/zi0Zje29CWFuUM3o11W6nzieBGOP4xv0JgpAvon31uaczXwXZhv6bplVwWACSLewtLALqu51pprVORsYvqs5Jpk5dFiNHBa102SRyYyZXCdFjPGp3P3SxR2BYjgGIbJjGrIFadPCr/D13fDzFGFe3+IKU2RwnhgpPMrVjy068JvurNte9c/N++s7Mb8ylhjomL7qD88Wk6ToBv4l3qq48=
notifications:
  slack:
    secure: u9o7XjspcNQ3gIoylKl7N2VeV3+toGzEU8or77q4WgZzP9keJZVzVH8NOYmuIVnMQ2H05GUxzearwx50hMBgHmDrL1Gp5+wpoZAuvQsKtbw9F0hPL4m5yaKtRxEIGQtfp1odQZP4fzVQ0EYn1DyyHL6Lwg6RAQwd9p48ziv6mIk/6tx2CSWWFjdDQxJLIyWoIvmtEJPxQGbhY1yjU4Yadq48p4muIq27LlNj3q4JlGRwwdA0JEL7gXCOM8BtbTVIXs9XtFqXhGcAc7+1k/EwUqe6wpde9OadSP1qPhvGbI1J03n1MfWdG170vNdLwL0Q+i/C2sQFCGN1sy5t0THTDwetxfHQaDZZ4iGJyk7ZAex6j1ht9Hl8eJ6p5EZyMtihxXzfWP2doCDz/89m81bunKM6qQkEiGAUY8S5lf0E1K+TiZ5p0DUDHsvtHKK7r/hpHrOS5GlyonnBaD0+NAtXPc+20ucZ0u9fkh1YBCni1bFiaF/pd6S6JaDeTJx+Kko9wpIhiWu2IUL0Eq+zrOszbAfm1wNXc89naRj0BDYtm6ApKgXsYkH7Ndw6h00Ju2DGBmdpjHFAcEo5dP1rJwL6NSk1JWg0x9tZjqgthw+EeB2KVGN+6VZjhuDDWE6y2MbEJuHxghAyk0EYK7yPX0Z5SiQ2/oDNZdvGMYc9Rh6eba8=
